services:
  - type: web
    name: school-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sms.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sms.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString

databases:
  - name: school-db