# Generated by Django 5.0 on 2025-06-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_account_holder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ifsc_code',
        ),
    ]
