# Generated by Django 5.0 on 2025-06-26 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headmaster', '0005_rename_name_classsection_class_name'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='headmaster.classsection')),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
