# Generated by Django 5.0 on 2025-06-26 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headmaster', '0004_examschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classsection',
            old_name='name',
            new_name='class_name',
        ),
    ]
