# Generated by Django 5.0 on 2025-06-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_remove_notice_date_posted_notice_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='created_at',
            new_name='date_posted',
        ),
    ]
