# Generated by Django 5.0 on 2025-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
