# Generated by Django 5.0 on 2025-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
