# Generated by Django 5.0 on 2025-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0003_studentfee_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
