# Generated by Django 5.0 on 2025-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountant', '0004_studentfee_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalary',
            name='payslip_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
